config/routes.rb
Rails.application.routes.draw do
  #resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'sign_in', to: 'sessions#new', as: 'sign_in'
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :posts do
    get  'search',  on: :collection
  end

  resources :sessions, only: [:create, :destroy]

  root to: 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord

    #Relationship
    belongs_to :user
    has_one_attached :image

    before_validation :load_uuid

    # Validations
    validate  :acceptable_image
    validates :title,
              :content,
              :summary,
              :user,
              presence: true

    ##############

    def self.search(author, start_date, end_date, order_by)
        query = Post.all
        if author.present?
            query = query.joins(:user)
                         .where('users.name ILIKE ?', "%#{author}%")
        end
        if start_date.present? && start_date.present?
            query = query.where("posts.created_at BETWEEN ? AND ?", start_date, end_date )
        end
        if order_by.present?
            unless order_by == '0'
                query = query.joins(:user).order('users.name DESC')
            else
                query = query.joins(:user).order('users.name ASC')
            end
        end
        query
    end

    private

    def  load_uuid
       self.uuid = SecureRandom.uuid
    end

    def acceptable_image
	  return unless image.attached?

	  unless image.byte_size <= 1.megabyte
	    errors.add(:image, "is too big")
	  end

	  acceptable_types = ["image/jpeg", "image/png"]
	  unless acceptable_types.include?(image.content_type)
	    errors.add(:image, "must be a JPEG or PNG")
	  end
	end

end

app/models/user.rb
class User < ApplicationRecord


  #Validations
  validates :name, presence: true
  validates :name, length: { in: 2..100}

  #Relationship
  has_many :posts, dependent: :destroy


  #before
  #before_validation :load_uuid


  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	helper_method :current_user

	def logged_in?
        if !session[:user_id]
          print("User is not logged in")
          redirect_to sign_in_path
        end
    end

	def current_user
	    @current_user ||= User.find(session[:user_id]) if session[:user_id]
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :logged_in?

  def index
    @posts = Post.all
  end

  def show
  end

  def search
    @posts = Post.search(params[:author], params[:start_date], params[:end_date], params[:order_by])    
    respond_to do |format|
      format.html
      format.js { render :layout => false }
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Noticia Creada Correctamente" }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content, :summary, :user_id, :image)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in?, only: :destroy

  def new
  end

  def create
    user = User.from_omniauth(request.env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to sign_in_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <div class="card">
        <div class="card-body">
            <div class="d-sm-flex justify-content-center justify-content-sm-between">
                <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Noticias Internas, Copyright © 2022.</span>
            </div>
        </div>    
    </div>        
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#"> Noticias Internas</a>
  <div class="collapse navbar-collapse" id="">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active"></li>
    </ul>
    <div class="form-inline my-2 my-lg-0">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown" align="right">        
          Hola! <%= current_user.name %>,
          <%= link_to signout_path do %>
            <i class="icon-arrow-right"></i>Salir
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Noticias Internas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= tinymce_assets %>
    <script type="text/javascript" src="/assets/tinymce.js"></script>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container-scroller">
      <%= render "layouts/header" if current_user.present? %> 
      <div class="container-fluid page-body-wrapper">
        <div class="row w-100 mx-0">
          <div class="content-wrapper">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
    <%= render "layouts/footer" %> 
  </body>
</html>

app/views/posts/_form.html.erb
<div class="grid-margin stretch-card">
  <div class="card">
    <div class="card-body">
      <h4 class="card-title">Publicar Noticia</h4>
      <%= form_for(@post, url: posts_path, html: { id: 'formPost', class: 'forms-sample'} ) do |f| %> 
        <div class="form-group">
          <%= f.label :title, "Titular", class:"control-label"%>
          <%= f.text_field :title, class: "form-control", required: true %>
        </div>
        <div class="form-group">
          <%= f.label :summary, "Bajada", class:"control-label"%>
          <%= f.text_field :summary, class: "form-control", required: true, value:"" %>
        </div>
        <div class="form-group">
          <%= f.label :image, "Imagen"%><br>
          <div class="input-group col-xs-12">
            <%= f.file_field :image , class:"form-control file-upload-info", required: true%>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :content, "Contenido", class:"control-label"%>
          <%= f.text_area :content, class: "tinymce", cols:"20", rows:"20" %>
          <%= tinymce %>
        </div>
        <%= f.hidden_field :user_id, class: "form-control", value:current_user.id %>
        <div class="navbar-right">
          <%= f.submit "Publicar", class: "btn btn-primary" %>
          <%= link_to "Cancelar", posts_path, class:"btn btn-light" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/_post.html.erb
<div id="post_<%= post.id %>" class="row">
  <div class="col-md-12" style="border: 1px #dedede solid; padding:3em; background-color:#000">
    <div class="row">
        <%= image_tag post.image, style:"width: 100%; height: 600px;"%>
    </div>
  </div>
  <div class="col-md-12 mt-4">
    <div class="card">
      <div class="card-body">
        <h1 class="card-title" style="font-size:  1.875rem"><%= post.title %></h1>
        <h5 class="card-subtitle"><%= post.summary %></h5>
        <br>
        <p class="card-description">
          Autor: <%= post.user.name %>
        </p>
        <p class="card-description">
          Fecha Publicación: <%= post.created_at.to_date %>
        </p>
      </div>
      <div class="card-body">
        <blockquote class="blockquote ">
          <% if action_name == 'show' %>
            <%= simple_format post.content %>  
          <% end %>
        </blockquote>
      </div>
    </div>
  </div>
</div>

app/views/posts/_posts.html.erb
<div class="list-group">  
  <% @posts.each do |post| %>
    <%= link_to post , style:"color:#797a7b" do %>
      <div class="card mb-3" >
        <div class="row no-gutters">
          <div class="col-md-2">
            <%= image_tag(post.image.attached? ?  post.image : 'account-add-photo.svg' , style:"height: 100%" , class: "card-img") %>
          </div>
          <div class="col-md-10">
            <div class="card-body">
              <h5 class="card-title"><%= post.title%></h5>
              <br>
              <p class="card-text"><small class="text-muted">Publicado hace <%= time_ago_in_words(post.created_at) %></small></p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/posts/index.html.erb
<%= form_for("", url: search_posts_path, method:'get', remote: true, html: { id: 'posts_search', class: ''} ) do |f| %>
  <div class="grid-margin stretch-card" style="margin-top:50px">
    <div class="card">
      <div class="card-body">
        <!--<form class="form-inline">-->
          <div class="form-row">
            <div class="col-md-4">
              <label style="color: #605a5a; font-size: 11px;">Autor</label>
              <%= text_field_tag :author, params[:author], class:"form-control", placeholder:"Buscar por nombre de autor..."%>
            </div>
            <div class="col-md-3">
              <label style="color: #605a5a; font-size: 11px;">Fecha Inicio</label>
              <%= date_field_tag :start_date, params[:start_date], class:"form-control",  placeholder:"Fecha Inicio" %>
            </div>
            <div class="col-md-3">
              <label style="color: #605a5a; font-size: 11px;">Fecha Fin</label>
              <%= date_field_tag :end_date, params[:end_date], class:"form-control",  placeholder:"Fecha Fin" %>
            </div>
            <div class="col-md-2" align="center">
              <button type="submit" class="btn btn-primary mt-4 mb-2">Filtar</button>
            </div>
          </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-4" align="left">
        <%= link_to "Nueva Noticia", new_post_path, class:"btn btn-primary mb-5 mt-5"%>
    </div>
    <div class="col-4">
      <p class="mb-4 text-mute mt-5" align="right" tyle="color: #605a5a; font-size: 12px;">Ordenar autor de forma:</p>
    </div>
    <div class="col-4" align="right" >
      <%= select_tag :order_by, options_for_select([['Ascendente', 0],['Descendente',1]]), class:'form-control mb-5 mt-5' %>
    </div>
  </div>
<% end %>
<div class="row">
    <div id="list-posts" class="col-md-12">            
        <%= render partial: "posts" %>
    </div>
</div>

<p style="color: green"><%= notice %></p>

app/views/posts/new.html.erb
<small class="mb-4 text-muted">
  <%= link_to "<< Regresar a noticias", posts_path %>
</small>
<br></br>
<%= render "form", post: @post %>

app/views/posts/search.js.erb
$('#list-posts').html('<%= escape_javascript(render("posts")) %>');

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>
<small class="mb-4 text-muted">
  <%= link_to "<< Regresar a noticias", posts_path %>
</small>
<br></br>
<%= render @post %>